<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\Common.Dropbox\Common.Dropbox.csproj" />
      <ProjectReference Include="..\Wishlist.Contracts\Wishlist.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="Dropbox.Api" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.4" />
      <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    </ItemGroup>

</Project>
